linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    # - whitespace
    # - bodyclose
    # - scopelint
    # - unparam
    # - funlen
    # - lll
    # - godox
