FROM golang

ARG USE_CN_APT_SOURCES
RUN [ -z "$USE_CN_APT_SOURCES" ] || sed -r -i 's/(deb|security).debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y iproute2 iptables

WORKDIR /camo

ENV CAMO_PASSWORD=
ENV CAMO_HOST=
ENV CAMO_LOG_LEVEL=debug

EXPOSE 443

CMD [ "./docker-dev-entrypoint.sh" ]
