FROM golang

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y iproute2 iptables

WORKDIR /camo

EXPOSE 443

CMD [ "./docker-dev-entrypoint.sh" ]
